### ISSUE TITLE
Border issue in students

### ISSUE THREAD

**Issue by Crocmagnon** [BdEINSALyon/marsu#3]
There is a double border in students, and probably elsewhere. See screenshot :

![Screenshot](https://www.dropbox.com/s/p7jkbxu3lchaxtl/Capture%20d%27%C3%A9cran%202016-08-28%2014.36.39.png?raw=1)

**Comment by PhilippeGeek** [comment]
This bug is due to Bootstrap V4 Alpha, waiting from them
