### ISSUE TITLE
INSA Mail button won't work

### ISSUE THREAD

**Issue by Crocmagnon** [BdEINSALyon/marsu#4]
The mail generation button doesn't do anything.

Tried in Safari and Chrome on OS X 10.11.6 (El Capitan). Both browsers up to date.

![GIF](https://dl.dropboxusercontent.com/u/60903785/mail-generator.gif)

**Comment by PhilippeGeek** [comment]
This issue was due to TurboLink library, which goes crazy with page reloading and jquery initialization.
